# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ebf4a8pQwScpljDm3RDxZiitoLbJjgUj
"""

# ============================================================
# EXERCISE 01
# ImageNet Preprocessing and Visualization using VGG16
# ============================================================

# STEP 1: INSTALL LIBRARY
!pip install -q tensorflow-datasets importlib_resources

# STEP 2: IMPORT LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds

from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input, decode_predictions


# ============================================================
# STEP 3: LOAD IMAGENETTE DATASET
# ============================================================

(train_ds, test_ds), info = tfds.load(
    "imagenette/320px-v2",
    split=["train", "validation"],
    as_supervised=True,
    with_info=True
)

class_names = [
    "tench",
    "English springer",
    "cassette player",
    "chain saw",
    "church",
    "French horn",
    "garbage truck",
    "gas pump",
    "golf ball",
    "parachute"
]

print("Dataset loaded!")
print("Number of classes:", len(class_names))
print("Training images:", info.splits["train"].num_examples)
print("Testing images :", info.splits["validation"].num_examples)


# ============================================================
# STEP 4: SELECT 20 IMAGES PER CLASS
# ============================================================

images = []
labels = []

count = [0] * 10

for image, label in train_ds:

    label = int(label.numpy())

    if count[label] < 20:
        images.append(image.numpy())
        labels.append(label)
        count[label] += 1

    if all(c == 20 for c in count):
        break

labels = np.array(labels)

print("\nImages selected:", len(images))


# ============================================================
# STEP 5: DISPLAY 10 RANDOM IMAGES
# ============================================================

np.random.seed(42)
indices = np.random.choice(len(images), 10, replace=False)

plt.figure(figsize=(12, 7))

for i, index in enumerate(indices):
    plt.subplot(2, 5, i + 1)
    plt.imshow(images[index])
    plt.title(class_names[labels[index]])
    plt.axis("off")

plt.suptitle("Images from Imagenette Dataset")
plt.tight_layout()
plt.show()


# ============================================================
# STEP 6: LOAD PRETRAINED VGG16
# ============================================================

model = VGG16(
    weights="imagenet",
    include_top=True
)

print("\nVGG16 loaded successfully!")
print("Input size:", model.input_shape)
print("Output size:", model.output_shape)


# ============================================================
# STEP 7: SELECT ONE IMAGE
# ============================================================

index = indices[0]

original_image = images[index]
original_label = class_names[labels[index]]

print("\nOriginal class:", original_label)
print("Original shape:", original_image.shape)

plt.figure(figsize=(5, 5))
plt.imshow(original_image)
plt.title("Original Image: " + original_label)
plt.axis("off")
plt.show()


# ============================================================
# STEP 8: RESIZE IMAGE TO 224 × 224
# ============================================================

image = tf.image.resize(
    original_image,
    (224, 224)
).numpy()

print("Resized shape:", image.shape)

plt.figure(figsize=(5, 5))
plt.imshow(image.astype(np.uint8))
plt.title("Resized Image: 224 × 224")
plt.axis("off")
plt.show()


# ============================================================
# STEP 9: PREPROCESS IMAGE
# ============================================================

image = image.astype(np.float32)

# Add batch dimension
image_batch = np.expand_dims(image, axis=0)

# VGG16 preprocessing
processed_image = preprocess_input(image_batch)

print("\nPreprocessed shape:", processed_image.shape)
print("Minimum value:", processed_image.min())
print("Maximum value:", processed_image.max())


# ============================================================
# STEP 10: PREDICT USING VGG16
# ============================================================

prediction = model.predict(
    processed_image,
    verbose=0
)

print("\nPrediction shape:", prediction.shape)


# ============================================================
# STEP 11: GET TOP-5 PREDICTIONS
# ============================================================

top5 = decode_predictions(
    prediction,
    top=5
)[0]

print("\nTop-5 Predictions:")

for i, (_, name, probability) in enumerate(top5, 1):
    print(
        f"{i}. {name:25s} "
        f"{probability * 100:.2f}%"
    )


# ============================================================
# STEP 12: VISUALIZE TOP-5 PREDICTIONS
# ============================================================

names = [item[1] for item in top5]
probabilities = [item[2] for item in top5]

plt.figure(figsize=(9, 5))

plt.bar(names, probabilities)

plt.xlabel("ImageNet Class")
plt.ylabel("Confidence")
plt.title("Top-5 VGG16 Predictions")

plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()


# ============================================================
# STEP 13: COMPARE ORIGINAL AND PREDICTED CLASS
# ============================================================

print("\nOriginal class :", original_label)
print("Predicted class:", top5[0][1])
print("Confidence     :", f"{top5[0][2] * 100:.2f}%")


# ============================================================
# STEP 14: EXTRACT FEATURE MAPS
# ============================================================

feature_model = tf.keras.Model(
    inputs=model.input,
    outputs=model.get_layer("block1_conv2").output
)

features = feature_model.predict(
    processed_image,
    verbose=0
)

feature_maps = features[0]

print("\nFeature map shape:", feature_maps.shape)


# ============================================================
# STEP 15: DISPLAY FIRST 16 FEATURE MAPS
# ============================================================

plt.figure(figsize=(10, 10))

for i in range(16):
    plt.subplot(4, 4, i + 1)

    plt.imshow(
        feature_maps[:, :, i],
        cmap="viridis"
    )

    plt.title(f"Map {i + 1}")
    plt.axis("off")

plt.suptitle("VGG16 Feature Maps - block1_conv2")
plt.tight_layout()
plt.show()


# ============================================================
# STEP 16: CHECK REPRESENTATIONS FROM DIFFERENT LAYERS
# ============================================================

layers = [
    "block1_conv2",
    "block2_conv2",
    "block3_conv3",
    "block4_conv3",
    "block5_conv3"
]

print("\nVGG16 Layer Representations:")

for layer in layers:

    feature_model = tf.keras.Model(
        inputs=model.input,
        outputs=model.get_layer(layer).output
    )

    output = feature_model.predict(
        processed_image,
        verbose=0
    )

    print(layer, "->", output.shape)


# ============================================================
# STEP 17: FINAL SUMMARY
# ============================================================

print("\n======================================")
print("EXPERIMENT SUMMARY")
print("======================================")

print("Dataset          : Imagenette")
print("Classes          :", len(class_names))
print("Images used      :", len(images))
print("CNN              : VGG16")
print("Pretrained on    : ImageNet")
print("Input size       : 224 × 224 × 3")
print("Output classes   : 1000")
print("Top predictions  : 5")
print("Feature layer    : block1_conv2")

print("""
Conclusion:
The Imagenette images were loaded and visualized.
The images were resized to 224 × 224 and preprocessed
according to the VGG16 requirements.

The pretrained VGG16 model classified the image into
1000 ImageNet classes and produced the Top-5 predictions.

Feature maps were also extracted from the convolutional
layers. Early layers of VGG16 learn simple features such
as edges, lines and textures, while deeper layers learn
more complex visual patterns.
""")

# ============================================================
# EXERCISE 02
# Visualization of Convolutional Filters and Feature Maps
# Using Pre-trained VGG16
# ============================================================

# STEP 1: INSTALL LIBRARY
!pip install -q tensorflow-datasets

# STEP 2: IMPORT LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds

from tensorflow.keras.applications import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input


# ============================================================
# STEP 3: LOAD IMAGENETTE DATASET
# ============================================================

(train_ds, test_ds), info = tfds.load(
    "imagenette/320px-v2",
    split=["train", "validation"],
    as_supervised=True,
    with_info=True
)

class_names = [
    "tench",
    "English springer",
    "cassette player",
    "chain saw",
    "church",
    "French horn",
    "garbage truck",
    "gas pump",
    "golf ball",
    "parachute"
]

print("Dataset loaded!")
print("Number of classes:", len(class_names))


# ============================================================
# STEP 4: SELECT SOME IMAGES
# ============================================================

images = []
labels = []
count = [0] * 10

for image, label in train_ds:

    label = int(label.numpy())

    if count[label] < 5:
        images.append(image.numpy())
        labels.append(label)
        count[label] += 1

    if all(c == 5 for c in count):
        break

print("Images selected:", len(images))


# ============================================================
# STEP 5: LOAD PRETRAINED VGG16
# ============================================================

model = VGG16(
    weights="imagenet",
    include_top=True
)

print("VGG16 loaded!")
print("Input shape :", model.input_shape)
print("Output shape:", model.output_shape)


# ============================================================
# STEP 6: SELECT ONE IMAGE
# ============================================================

np.random.seed(42)

index = np.random.randint(len(images))

original_image = images[index]
original_label = class_names[labels[index]]
print("\nOriginal class:", original_label)
print("Original shape:", original_image.shape)

plt.figure(figsize=(5, 5))
plt.imshow(original_image)
plt.title("Input Image: " + original_label)
plt.axis("off")
plt.show()


# ============================================================
# STEP 7: RESIZE AND PREPROCESS IMAGE
# ============================================================

image = tf.image.resize(
    original_image,
    (224, 224)
).numpy()

image = image.astype(np.float32)

# Add batch dimension
image = np.expand_dims(image, axis=0)

# VGG16 preprocessing
processed_image = preprocess_input(image)

print("\nProcessed image shape:", processed_image.shape)


# ============================================================
# STEP 8: SELECT THREE VGG16 LAYERS
# ============================================================

layers = [
    "block1_conv2",   # Early layer
    "block3_conv3",   # Intermediate layer
    "block5_conv3"    # Deep layer
]

print("\nSelected layers:")

for name in layers:
    print(name, "->", model.get_layer(name).output.shape)


# ============================================================
# STEP 9: EXTRACT FEATURE MAPS
# ============================================================

feature_model = tf.keras.Model(
    inputs=model.input,
    outputs=[
        model.get_layer(name).output
        for name in layers
    ]
)

features = feature_model.predict(
    processed_image,
    verbose=0
)

early = features[0][0]
middle = features[1][0]
deep = features[2][0]

print("\nFeature map shapes:")
print("Early        :", early.shape)
print("Intermediate :", middle.shape)
print("Deep         :", deep.shape)


# ============================================================
# STEP 10: VISUALIZE FEATURE MAPS
# ============================================================

feature_data = [
    ("Early - block1_conv2", early),
    ("Intermediate - block3_conv3", middle),
    ("Deep - block5_conv3", deep)
]

for title, feature in feature_data:

    plt.figure(figsize=(10, 8))

    for i in range(8):
        plt.subplot(2, 4, i + 1)

        plt.imshow(
            feature[:, :, i],
            cmap="viridis"
        )

        plt.title("Map " + str(i + 1))
        plt.axis("off")

    plt.suptitle(title)
    plt.tight_layout()
    plt.show()


# ============================================================
# STEP 11: EXTRACT LEARNED FILTERS
# ============================================================

conv_layer = model.get_layer("block1_conv1")

weights, biases = conv_layer.get_weights()

print("\nFilter information:")
print("Filter shape:", weights.shape)
print("Bias shape  :", biases.shape)


# ============================================================
# STEP 12: NORMALIZE FILTERS
# ============================================================

filters = weights

filters = (
    filters - filters.min()
) / (
    filters.max() - filters.min()
)


# ============================================================
# STEP 13: VISUALIZE FIRST 32 FILTERS
# ============================================================

plt.figure(figsize=(12, 7))

for i in range(32):

    plt.subplot(4, 8, i + 1)

    plt.imshow(filters[:, :, :, i])

    plt.title("Filter " + str(i + 1))
    plt.axis("off")

plt.suptitle("VGG16 Learned Filters - block1_conv1")
plt.tight_layout()
plt.show()


# ============================================================
# STEP 14: SUMMARY
# ============================================================

print("\n======================================")
print("EXPERIMENT SUMMARY")
print("======================================")

print("Dataset       : Imagenette")
print("CNN           : VGG16")
print("Pretrained on : ImageNet")
print("Input size    : 224 × 224 × 3")

print("\nFeature Maps:")
print("block1_conv2 :", early.shape)
print("block3_conv3 :", middle.shape)
print("block5_conv3 :", deep.shape)

print("\nFilters:")
print("Layer         : block1_conv1")
print("Number        : 64")
print("Size          : 3 × 3 × 3")

print("""
Conclusion:
The feature maps of different VGG16 layers were visualized.

Early layers detect simple features such as edges, colors
and textures. Intermediate layers detect shapes and object
parts, while deeper layers learn more complex and semantic
features.

The learned convolutional filters from the first layer were
also visualized.
""")
